# Generated by Django 4.2.11 on 2024-04-16 15:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='classes',
            name='class_teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='class_teacher', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='subclasses',
            name='subclass_teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subclass_teacher', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='subclasses',
            name='subclass_code',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterUniqueTogether(
            name='subclasses',
            unique_together={('subclass_name', 'subclass_code')},
        ),
    ]
